/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          lime: '#84CC16',
        },
        'electric-dark': '#121413',
        'card-bg': '#1E1F1E',
        // New design system — Material 3 Dark
        'on-primary-fixed-variant': '#0038b6',
        'on-tertiary-fixed': '#002113',
        tertiary: '#005a3c',
        'surface-variant': '#232630',
        'on-secondary-fixed': '#141b2c',
        'on-secondary': '#ffffff',
        'on-primary-container': '#dfe3ff',
        'primary-container': '#84CC16',
        'on-error': '#ffffff',
        'on-tertiary-container': '#72fec0',
        'surface-dim': '#1a1b21',
        'on-secondary-fixed-variant': '#3f4759',
        'surface-container': '#1d1f27',
        'on-secondary-container': '#5d6478',
        'surface-container-high': '#232630',
        'surface-container-highest': '#2e323e',
        'secondary-fixed': '#dbe2fa',
        secondary: '#a1a8c0',
        primary: '#84CC16',
        surface: '#121318',
        'on-primary': '#000000',
        'inverse-on-surface': '#eaf1ff',
        'secondary-fixed-dim': '#bfc6dd',
        outline: '#737688',
        'secondary-container': '#2e323e',
        'tertiary-container': '#007550',
        'on-primary-fixed': '#001452',
        'surface-bright': '#333642',
        'inverse-surface': '#213145',
        'surface-tint': '#004ced',
        'surface-container-low': '#1a1b21',
        'outline-variant': '#434656',
        'on-tertiary': '#ffffff',
        'inverse-primary': '#b7c4ff',
        'tertiary-fixed': '#6ffbbe',
        'primary-fixed': '#dde1ff',
        'surface-container-lowest': '#121318',
        'tertiary-fixed-dim': '#4edea3',
        'on-surface-variant': '#c3c5d9',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#b7c4ff',
        'on-background': '#ffffff',
        error: '#ba1a1a',
        'on-tertiary-fixed-variant': '#005236',
        'on-surface': '#ffffff',
        background: '#121318',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
        'headline-lg-mobile': ['Manrope'],
        'body-md': ['Inter'],
        'label-md': ['Inter'],
        'body-sm': ['Inter'],
        'headline-lg': ['Manrope'],
        'body-lg': ['Inter'],
        'label-sm': ['Inter'],
        'headline-md': ['Manrope'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        sm: '8px',
        'container-margin': '20px',
        lg: '24px',
        base: '4px',
        xs: '4px',
        xl: '32px',
        md: '16px',
        gutter: '16px',
      },
    },
  },
  plugins: [],
};
